# Author:  PH01L
# Email:   phoil@osrsbox.com
# Website: https://www.osrsbox.com
#
# Description:
# Dockerfile for osrsbox-api
#
# Copyright (c) 2021, PH01L
# 
###############################################################################
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################
services:
  mongo:
    container_name: osrsbox-api-mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: [--auth]
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      PROJECT_USERNAME: ${PROJECT_USERNAME}
      PROJECT_PASSWORD: ${PROJECT_PASSWORD}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongo/create-database.sh:/docker-entrypoint-initdb.d/create-database.sh:ro
    networks:
      - backend
      - runemanager

  eve:
    build:
      context: eve
      dockerfile: Dockerfile
    container_name: osrsbox-api-eve
    image: python:3.7-alpine
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGO_URI: "mongodb://mongo/db"
      MONGO_PORT: ${MONGO_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      PROJECT_USERNAME: ${PROJECT_USERNAME}
      PROJECT_PASSWORD: ${PROJECT_PASSWORD}
    volumes:
      - ./eve:/var/www/eve
      - ./eve/scripts:/scripts
    depends_on:
      - mongo
    networks:
      - backend

#  nginx:
#    container_name: osrsbox-api-nginx
#    image: nginx:stable-alpine
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#      - "443:443"
#    volumes:
#      # - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/conf.d/app.dev.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/app:/usr/share/nginx/html/
#      - /etc/letsencrypt/:/etc/nginx/certs/
#    depends_on:
#      - eve
#    networks:
#      - frontend
#      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  runemanager:
    name: osrsbox
    driver: bridge
